//
//  CustomKeyboardTests.swift
//  CustomKeyboardTests
//
//  Created by 이경민 on 2022/07/15.
//

import XCTest

class CustomKeyboardTests: XCTestCase {
    var viewModel: KeyboardViewModel!
    typealias Buffer = (chosung: Chosung?, jungsung: Jungsung?, jongsung: Jongsung?)
    
    override func setUpWithError() throws {
        viewModel = KeyboardViewModel()
    }

    override func tearDownWithError() throws {
        viewModel = nil
    }

    func test_동() {
        let expected = """
것은싹이그들의들어물방아천하를때까지인간이끓는다뭇되려니와끓는눈에살같이없으면품었기있음으로써듣는다미묘한무엇을청춘의이것이야말로이상은되려니와드니고불어봄바람이다생명을힘차게가진예수는미묘한것이피가하여도어디이것이다얼음열락의물방아품에전인그들은쓸쓸하랴
"""
        let buffers: [Buffer] = [
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅆ, nil, .ㅆ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅡ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㅊ, nil, .ㅊ),
            (nil, .ㅓ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅐ, nil),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅏ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅎ, nil, .ㅎ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅕ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅗ, nil),
            (nil, .ㅏ, nil),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅎ, nil, .ㅎ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅌ, nil, .ㅌ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅕ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅜ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅗ, nil),
            (.ㅆ, nil, .ㅆ),
            (nil, .ㅓ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄷ, nil, .ㄷ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅛ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅊ, nil, .ㅊ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅊ, nil, .ㅊ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅑ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅗ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅕ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅗ, nil),
            (nil, .ㅏ, nil),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅗ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅗ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅏ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅐ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅕ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅊ, nil, .ㅊ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅔ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅖ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅛ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅕ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅕ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅜ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅓ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅡ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅆ, nil, .ㅆ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅆ, nil, .ㅆ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅑ, nil),
        ]
        
        buffers.forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        XCTAssertEqual(expected, viewModel.result.value)
    }
    
//    func test_동이아닐경우() {
//        let expected = "동"
//        let keyboards = [keyBoardㄷ,keyBoardㅇ,keyBoardㅗ]
//        
//        keyboards.forEach { button in
//            viewModel.didTapKeyboardButton(sender: button)
//        }
//        
//        XCTAssertNotEqual(expected, viewModel.result.value)
//    }
}
