//
//  CustomKeyboardTests.swift
//  CustomKeyboardTests
//
//  Created by 이경민 on 2022/07/15.
//

import XCTest
@testable import CustomKeyboard

class CustomKeyboardTests: XCTestCase {
    var viewModel: KeyboardViewModel!
    typealias Buffer = (chosung: Chosung?, jungsung: Jungsung?, jongsung: Jongsung?)
    
    override func setUpWithError() throws {
        viewModel = KeyboardViewModel()
    }
    
    override func tearDownWithError() throws {
        viewModel = nil
    }
    
    //    func test_동() {
    //        let expected = """
    //청춘의없는바이며이상은위하여끓는구하기시들어있다그들의끓는인생을주는눈에고행을것이다부패를있는열매를그것은가는교향악이다그들은사라지지가치를그와있는자신과소리다이것은봄바람이다청춘에서만얼마나밝은방황하였으며말이다
    //"""
    //        let buffers: [Buffer] = [
    //            (.ㅊ, nil, .ㅊ),
    //            (nil, .ㅓ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅊ, nil, .ㅊ),
    //            (nil, .ㅜ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (nil, .ㅣ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅓ, nil),
    //            (.ㅂ, nil, .ㅂ),
    //            (.ㅅ, nil, .ㅅ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅕ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅜ, nil),
    //            (nil, .ㅣ, nil),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅕ, nil),
    //            (.ㄲ, nil, .ㄲ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅎ, nil, .ㅎ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅜ, nil),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅏ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅣ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅓ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㅆ, nil, .ㅆ),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅡ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (nil, .ㅣ, nil),
    //            (.ㄲ, nil, .ㄲ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅎ, nil, .ㅎ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅐ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅈ, nil, .ㅈ),
    //            (nil, .ㅜ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅜ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅔ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅗ, nil),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅐ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅓ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅜ, nil),
    //            (.ㅍ, nil, .ㅍ),
    //            (nil, .ㅐ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㅆ, nil, .ㅆ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅕ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅐ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅡ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅓ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅏ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅛ, nil),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅑ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅏ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅡ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅏ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅏ, nil),
    //            (.ㅈ, nil, .ㅈ),
    //            (nil, .ㅣ, nil),
    //            (.ㅈ, nil, .ㅈ),
    //            (nil, .ㅣ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅏ, nil),
    //            (.ㅊ, nil, .ㅊ),
    //            (nil, .ㅣ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅡ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅡ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅗ, nil),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㅆ, nil, .ㅆ),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅈ, nil, .ㅈ),
    //            (nil, .ㅏ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅣ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅗ, nil),
    //            (nil, .ㅏ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅗ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄱ, nil, .ㄱ),
    //            (nil, .ㅓ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅗ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅏ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (nil, .ㅏ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //            (.ㅊ, nil, .ㅊ),
    //            (nil, .ㅓ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅊ, nil, .ㅊ),
    //            (nil, .ㅜ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅔ, nil),
    //            (.ㅅ, nil, .ㅅ),
    //            (nil, .ㅓ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅏ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅓ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅏ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (nil, .ㅏ, nil),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅏ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㄱ, nil, .ㄱ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㄴ, nil, .ㄴ),
    //            (.ㅂ, nil, .ㅂ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅗ, nil),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (.ㅎ, nil, .ㅎ),
    //            (nil, .ㅏ, nil),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅕ, nil),
    //            (.ㅆ, nil, .ㅆ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅡ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅕ, nil),
    //            (.ㅁ, nil, .ㅁ),
    //            (nil, .ㅏ, nil),
    //            (.ㄹ, nil, .ㄹ),
    //            (.ㅇ, nil, .ㅇ),
    //            (nil, .ㅣ, nil),
    //            (.ㄷ, nil, .ㄷ),
    //            (nil, .ㅏ, nil),
    //        ]
    //
    //        buffers.forEach { buffer in
    //            viewModel.didTapKeyboardButton(buffer: buffer)
    //        }
    //
    //        XCTAssertEqual(expected, viewModel.result.value)
    //    }
    
    func test_동이아닐경우() {
        let expected = "빢께삐온따"
        let buffers: [Buffer] = [
            (.ㅃ, nil, .ㅂ),
            (nil, .ㅏ, nil),
            (.ㄲ, nil, .ㄲ),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅔ, nil),
            (.ㅃ, nil, .ㅂ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅗ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅏ, nil),
        ]
        buffers.forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        XCTAssertEqual(expected, viewModel.result.value)
    }
    
    func test_지웠다쓰는경우() {
        make()
        viewModel.isRemovePhoneme = true
        let expected = "없어없다없을"
//        viewModel.result.value = expected
        (0..<3).forEach { _ in
            viewModel.didTapBack()
        }
        [(.ㅇ, nil, .ㅇ),(nil, .ㅡ, nil),(.ㄹ, nil, .ㄹ)].forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        XCTAssertEqual(expected, viewModel.result.value)
    }
    
    func test_지우는경우() {
        make()
        viewModel.isRemovePhoneme = true
        let expected = "없어없다없"
//        viewModel.result.value = expected
        (0..<3).forEach { _ in
            viewModel.didTapBack()
        }
        
        XCTAssertEqual(expected, viewModel.result.value)
    }
    
    //viewModel에 기본 데이터를 만드는 함수
    func make() {
        let buffers: [Buffer] = [
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㅅ, nil, .ㅅ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ)
        ]

        buffers.forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        print(viewModel.result.value)
    }
    
    func test_지우는경우2() {
        let expected = "없어없다업"
        let buffers: [Buffer] = [
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂㅅ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㄹ, nil, .ㄹ),
        ]
        
        buffers.forEach {
            viewModel.didTapKeyboardButton(buffer: $0)
        }
        for _ in 1...7 {
            viewModel.didTapBack()
        }
        
        XCTAssertEqual(expected, viewModel.result.value)
    }
    
    func test_긴글1() {
        
        let expacted = """
어머니지나고북간도에계십니다덮어같이토끼그러나새겨지는묻힌노새소녀들의봅니다헤는시와하나의가득경헤일이름과까닭이요있습니다된가을계집애들의한이름과같이별이있습니다새워것은계집애들의오면이름자를아스라히별들을별이듯합니다보고속의이런마디씩까닭이요그러나너무나오는거외다못이웃소녀들의까닭입니다언덕하나의새워나는북간도에된하늘에는있습니다나는패오는봄이이름과덮어새워내린보고있습니다지나고옥때우는나의겨울이프랑시스아직까닭입니다
"""

        let buffers: [Buffer] = [
            
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅓ, nil),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅜ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅗ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅔ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅖ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅓ, nil),
                (.ㅍ, nil, .ㅍ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅓ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㅌ, nil, .ㅌ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅌ, nil, .ㅌ),
                (nil, .ㅗ, nil),
                (.ㄲ, nil, .ㄲ),
                (nil, .ㅣ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅐ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅕ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅜ, nil),
                (.ㄷ, nil, .ㄷ),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅗ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅐ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅗ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅕ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅗ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅔ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (nil, .ㅏ, nil),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅕ, nil),
                (.ㅇ, nil, .ㅇ),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅔ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅡ, nil),
                (.ㅁ, nil, .ㅁ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (nil, .ㅏ, nil),
                (.ㄲ, nil, .ㄲ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅛ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅆ, nil, .ㅆ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅗ, nil),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅖ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅐ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅡ, nil),
                (.ㅁ, nil, .ㅁ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (nil, .ㅏ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㅌ, nil, .ㅌ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅕ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅆ, nil, .ㅆ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅐ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (nil, .ㅓ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅓ, nil),
                (.ㅅ, nil, .ㅅ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅖ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅐ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅕ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅡ, nil),
                (.ㅁ, nil, .ㅁ),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅏ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅏ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅏ, nil),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅕ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅕ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㅅ, nil, .ㅅ),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅏ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅗ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅗ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅣ, nil),
                (.ㅆ, nil, .ㅆ),
                (nil, .ㅣ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄲ, nil, .ㄲ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅛ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅓ, nil),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅜ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅓ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅁ, nil, .ㅁ),
                (nil, .ㅗ, nil),
                (.ㅅ, nil, .ㅅ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (.ㅅ, nil, .ㅅ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅗ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅕ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㄲ, nil, .ㄲ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅓ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅐ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅜ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅗ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅔ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅗ, nil),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅎ, nil, .ㅎ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅔ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅆ, nil, .ㅆ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅍ, nil, .ㅍ),
                (nil, .ㅐ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅗ, nil),
                (.ㅁ, nil, .ㅁ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅡ, nil),
                (.ㅁ, nil, .ㅁ),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅓ, nil),
                (.ㅍ, nil, .ㅍ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅓ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅐ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (nil, .ㅓ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅐ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㅂ, nil, .ㅂ),
                (nil, .ㅗ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅆ, nil, .ㅆ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅗ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅗ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄸ, nil, .ㄷ),
                (nil, .ㅐ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅡ, nil),
                (.ㄴ, nil, .ㄴ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅡ, nil),
                (nil, .ㅣ, nil),
                (.ㄱ, nil, .ㄱ),
                (nil, .ㅕ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅜ, nil),
                (.ㄹ, nil, .ㄹ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅍ, nil, .ㅍ),
                (nil, .ㅡ, nil),
                (.ㄹ, nil, .ㄹ),
                (nil, .ㅏ, nil),
                (.ㅇ, nil, .ㅇ),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅣ, nil),
                (.ㅅ, nil, .ㅅ),
                (nil, .ㅡ, nil),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅏ, nil),
                (.ㅈ, nil, .ㅈ),
                (nil, .ㅣ, nil),
                (.ㄱ, nil, .ㄱ),
                (.ㄲ, nil, .ㄲ),
                (nil, .ㅏ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil),
                (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
                (.ㅇ, nil, .ㅇ),
                (nil, .ㅣ, nil),
                (.ㅂ, nil, .ㅂ),
                (.ㄴ, nil, .ㄴ),
                (nil, .ㅣ, nil),
                (.ㄷ, nil, .ㄷ),
                (nil, .ㅏ, nil)
            
            
        ]
        
        buffers.forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        XCTAssertEqual(expacted, viewModel.result.value)
    }
    
    func test_긴글2() {
        let expacted = """
지나고옥때우는나의겨울이프랑시스아직까닭입니다하나에사람들의걱정도된하나에같이있습니다아름다운이런어머니릴케까닭입니다가을로아름다운딴은하나의애기아침이무성할하나에우는버리었습니다다하지불러없이내버리었습니다아름다운남은무덤파란별들을마디씩있습니다강아지풀이노루딴은까닭입니다가난한이국이름과버리었습니다봄이된위에도헤일까닭입니다
"""
        let buffers: [Buffer] = [
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅗ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅗ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅐ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅕ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅣ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅏ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅓ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅌ, nil, .ㅌ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅓ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅓ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅋ, nil, .ㅋ),
            (nil, .ㅔ, nil),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅗ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅐ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㅊ, nil, .ㅊ),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅓ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅓ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅂ, nil, .ㅂ),(.ㅅ, nil, .ㅅ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅐ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅓ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅜ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅓ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅕ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅁ, nil, .ㅁ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅣ, nil),
            (.ㅆ, nil, .ㅆ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㅇ, nil, .ㅇ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅏ, nil),
            (.ㅈ, nil, .ㅈ),
            (nil, .ㅣ, nil),
            (.ㅍ, nil, .ㅍ),
            (nil, .ㅜ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅗ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅜ, nil),
            (.ㄸ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅡ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅏ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅜ, nil),
            (.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅡ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㄱ, nil, .ㄱ),
            (nil, .ㅗ, nil),
            (nil, .ㅏ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅓ, nil),
            (.ㄹ, nil, .ㄹ),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅓ, nil),
            (.ㅆ, nil, .ㅆ),
            (.ㅅ, nil, .ㅅ),
            (nil, .ㅡ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㅂ, nil, .ㅂ),
            (nil, .ㅗ, nil),
            (.ㅁ, nil, .ㅁ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (nil, .ㅣ, nil),
            (.ㄴ, nil, .ㄴ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅜ, nil),
            (nil, .ㅣ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅔ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅗ, nil),
            (.ㅎ, nil, .ㅎ),
            (nil, .ㅔ, nil),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㄹ, nil, .ㄹ),
            (.ㄲ, nil, .ㄲ),
            (nil, .ㅏ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
            (.ㄹ, nil, .ㄹ),(.ㄱ, nil, .ㄱ),
            (.ㅇ, nil, .ㅇ),
            (nil, .ㅣ, nil),
            (.ㅂ, nil, .ㅂ),
            (.ㄴ, nil, .ㄴ),
            (nil, .ㅣ, nil),
            (.ㄷ, nil, .ㄷ),
            (nil, .ㅏ, nil),
        ]
        
        buffers.forEach { buffer in
            viewModel.didTapKeyboardButton(buffer: buffer)
        }
        
        XCTAssertEqual(expacted, viewModel.result.value)
    }
}
